COCICCS-5083:T-Vault (AAD): Show the list of AAD Service Principals in owner page
tmobile/t-vault pull request #580
Opened 2020-11-19 13:55 UTC by msivatmob

2020-11-19 13:56 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/tmobile/t-vault?pullRequest=580) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/tmobile/t-vault?pullRequest=580) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/tmobile/t-vault?pullRequest=580) it.</sub>

2020-11-20 02:21 UTC, sarathmohan4 requested changes

2020-11-20 02:21 UTC, sarathmohan4 commented on tvaultapi/src/main/java/com/tmobile/cso/vault/api/service/AzureServicePrinicipalAccountsService.java
> +		if (HttpStatus.OK.equals(response.getHttpstatus())) {
This check is always true, is it required?

2020-11-20 02:21 UTC, sarathmohan4 commented on tvaultapi/src/main/resources/application.properties
> +ldap.url=
additional spaces,

2020-11-20 02:21 UTC, sarathmohan4 commented on tvaultapi/src/main/resources/application.properties
> +workload.endpoint=
additional space

2020-11-20 02:21 UTC, sarathmohan4 commented on tvaultapi/src/main/resources/application.properties
> +sslcertmanager.domain=
additional space

2020-11-20 02:21 UTC, sarathmohan4 commented on tvaultui/src/app/Features/admin/admin.controller.js
>                 return iampagesShown < ($scope.numOfIamSvcaccs / iampageSize);
iampagesShown , using same variable might impact padination in IAM lisiting

2020-11-20 09:59 UTC, msivatmob commented on tvaultapi/src/main/resources/application.properties
> +workload.endpoint=
resolved

2020-11-20 09:59 UTC, msivatmob commented on tvaultui/src/app/Features/admin/admin.controller.js
>                 return iampagesShown < ($scope.numOfIamSvcaccs / iampageSize);
changed the variable name to azurepagesshown.

2020-11-20 10:07 UTC, sarathmohan4 requested changes

2020-11-20 10:07 UTC, sarathmohan4 commented on tvaultui/src/app/Features/admin/admin.jade
> +                                      span.svc-collapse-link(ng-click="collapseNoteIAM()") >>
collapseNoteIAM() and isCollapsedIAM is already used in IAM tab, might need to use a new function and variable here

2020-11-20 12:56 UTC, msivatmob commented on tvaultui/src/app/Features/admin/admin.jade
> +                                      span.svc-collapse-link(ng-click="collapseNoteIAM()") >>
changed to collapseNoteAzure() and CollapsedAzure.

2020-11-23 06:14 UTC, merged

2020-11-23 06:15 UTC, alexrajan3 reviewed
Approved