COCICCS-2359:Logging enhancements - Safes added.
tmobile/t-vault pull request #625
Opened 2020-12-04 05:41 UTC by msivatmob

2020-12-04 05:41 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/tmobile/t-vault?pullRequest=625) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/tmobile/t-vault?pullRequest=625) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/tmobile/t-vault?pullRequest=625) it.</sub>

2020-12-07 03:11 UTC, alexrajan3 requested changes
Correct all the Code smells in logs (Remove the "toString()")

2020-12-07 03:11 UTC, alexrajan3 commented on tvaultapi/src/main/java/com/tmobile/cso/vault/api/service/AWSAuthService.java
> +				put(LogMessage.USER, ThreadLocalContext.getCurrentMap().get(LogMessage.USER).toString()).
Correct all the Code smells in logs (Remove the "toString()")

2020-12-07 06:45 UTC, msivatmob commented on tvaultapi/src/main/java/com/tmobile/cso/vault/api/service/AWSAuthService.java
> +				put(LogMessage.USER, ThreadLocalContext.getCurrentMap().get(LogMessage.USER).toString()).
removed toString().

2020-12-07 07:32 UTC, alexrajan3 requested changes

2020-12-07 07:32 UTC, alexrajan3 commented on tvaultapi/src/main/java/com/tmobile/cso/vault/api/service/SafesService.java
> -						put(LogMessage.MESSAGE, String.format ("Trying to update metadata [%s]", params.toString())).
toString() needed here to log the map object (params)

2020-12-07 07:32 UTC, alexrajan3 commented on tvaultapi/src/main/java/com/tmobile/cso/vault/api/service/SafesService.java
> +			      put(LogMessage.MESSAGE, String.format ("Trying to remove user from SDB [%s]]", safeUser.getPath())).
Extra square bracket

2020-12-07 07:32 UTC, alexrajan3 commented on tvaultapi/src/main/java/com/tmobile/cso/vault/api/service/SafesService.java
> +				put(LogMessage.MESSAGE, String.format ("Trying to Add AwsRole [%s] to Safe [%s]", awsRole.getRole(),awsRole.getPath())).
What will happened if awsRole object is null

2020-12-07 07:32 UTC, alexrajan3 commented on tvaultapi/src/main/java/com/tmobile/cso/vault/api/service/AWSAuthService.java
> +				put(LogMessage.MESSAGE, String.format("Trying to create AWS Role [%s]", awsLoginRole.getRole())).
What will happened if awsLoginRole object is null (Move the log after the request validation)

2020-12-08 10:19 UTC, msivatmob commented on tvaultapi/src/main/java/com/tmobile/cso/vault/api/service/SafesService.java
> -						put(LogMessage.MESSAGE, String.format ("Trying to update metadata [%s]", params.toString())).
toString added.

2020-12-08 10:19 UTC, msivatmob commented on tvaultapi/src/main/java/com/tmobile/cso/vault/api/service/SafesService.java
> +				put(LogMessage.MESSAGE, String.format ("Trying to Add AwsRole [%s] to Safe [%s]", awsRole.getRole(),awsRole.getPath())).
logs added after input validation.

2020-12-08 10:19 UTC, msivatmob commented on tvaultapi/src/main/java/com/tmobile/cso/vault/api/service/AWSAuthService.java
> +				put(LogMessage.MESSAGE, String.format("Trying to create AWS Role [%s]", awsLoginRole.getRole())).
logs added after input validation.

2020-12-08 10:20 UTC, msivatmob commented on tvaultapi/src/main/java/com/tmobile/cso/vault/api/service/SafesService.java
> +			      put(LogMessage.MESSAGE, String.format ("Trying to remove user from SDB [%s]]", safeUser.getPath())).
removed.

2020-12-09 04:59 UTC, alexrajan3 approved these changes

2020-12-09 04:59 UTC, merged