COCICCS-5048:Permissions given for approle not removed while deleting…
tmobile/t-vault pull request #645
Opened 2020-12-15 12:30 UTC by msivatmob

… approle from approle management tab

2020-12-15 12:30 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/tmobile/t-vault?pullRequest=645) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/tmobile/t-vault?pullRequest=645) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/tmobile/t-vault?pullRequest=645) it.</sub>

2020-12-16 05:14 UTC, alexrajan3 requested changes
Please correct all Sonar lint issues and add test cases for new changes

2020-12-16 07:22 UTC, msivatmob commented
> Please correct all Sonar lint issues and add test cases for new changes

removed Sonar lint issues and added test case for new changes.

2020-12-16 11:00 UTC, alexrajan3 approved these changes

2020-12-16 11:00 UTC, merged