COCICCS-5540:Changes in adding emails to notification list and splunk log issues.
tmobile/t-vault pull request #659
Opened 2020-12-22 07:47 UTC by msivatmob

2020-12-22 07:47 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/tmobile/t-vault?pullRequest=659) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/tmobile/t-vault?pullRequest=659) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/tmobile/t-vault?pullRequest=659) it.</sub>

2020-12-22 10:19 UTC, alexrajan3 requested changes
Please add enough Junit test cases to cover the new methods

2020-12-22 10:19 UTC, alexrajan3 commented on tvaultapi/src/main/java/com/tmobile/cso/vault/api/controller/OIDCUtil.java
> +							directoryGroupEmail.setId(null);
Why this value is set as null ? we are getting both "Id" and "email" from AAD rt ?

2020-12-22 10:19 UTC, alexrajan3 commented on tvaultapi/src/main/java/com/tmobile/cso/vault/api/service/OIDCAuthService.java
> +            groupsList.setValues(allGroups.toArray(new DirecotryGroupEmail[allGroups.size()]));
Null pointer exception could be thrown in allGroups.size()

2020-12-23 08:25 UTC, msivatmob commented on tvaultapi/src/main/java/com/tmobile/cso/vault/api/service/OIDCAuthService.java
> +            groupsList.setValues(allGroups.toArray(new DirecotryGroupEmail[allGroups.size()]));
checked.

2020-12-23 09:33 UTC, msivatmob commented on tvaultapi/src/main/java/com/tmobile/cso/vault/api/controller/OIDCUtil.java
> +							directoryGroupEmail.setId(null);
the id is not using so we can remove the null value.

2020-12-23 09:55 UTC, nithyal1 commented on tvaultapi/src/main/java/com/tmobile/cso/vault/api/controller/OIDCUtil.java
> +
Reduce the cognitive complexity to 15

2020-12-23 10:32 UTC, msivatmob commented on tvaultapi/src/main/java/com/tmobile/cso/vault/api/controller/OIDCUtil.java
> +
complexity reduced to 15.

2020-12-23 10:39 UTC, nithyal1 approved these changes

2020-12-23 10:46 UTC, sarathmohan4 approved these changes

2020-12-23 10:46 UTC, merged