COCICCS-5690:Capturing App name during safe creation,COCICCS-5681:Create AWS Roles,COCICCS-5896:Notification email Search by option issue & logging issues
tmobile/t-vault pull request #681
Opened 2021-01-07 10:00 UTC by msivatmob

2021-01-07 10:00 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/tmobile/t-vault?pullRequest=681) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/tmobile/t-vault?pullRequest=681) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/tmobile/t-vault?pullRequest=681) it.</sub>

2021-01-07 11:43 UTC, sarathmohan4 requested changes

2021-01-07 11:43 UTC, sarathmohan4 commented on tvaultapi/src/main/java/com/tmobile/cso/vault/api/common/TVaultConstants.java
> +    public static final String AWSIAM_USERS_METADATA_MOUNT_PATH = "metadata/awsroleiam_users";
One path is required that can have both ec2 and iam, so that a single api call will get all the aws roles of a user. Also ui might have single page for both ec2 and iam

2021-01-07 11:43 UTC, sarathmohan4 commented on tvaultapi/src/main/java/com/tmobile/cso/vault/api/controller/ControllerUtil.java
> +        AppRoleMetadataDetails appRoleMetadataDetails = new AppRoleMetadataDetails(RoleName);
better create a new model for awsrolemetadatadetails, which will be useful when using a single mount path for ec2 and iam. one method will be enough for populating metajson for both ec2 and iam, right?

2021-01-07 11:43 UTC, sarathmohan4 commented on tvaultapi/src/main/java/com/tmobile/cso/vault/api/controller/ControllerUtil.java
> +	/**
Better if we can put commit for single functionality change. Appname for safe creation is having changes of aws role creation

2021-01-07 13:10 UTC, msivatmob commented on tvaultapi/src/main/java/com/tmobile/cso/vault/api/common/TVaultConstants.java
> +    public static final String AWSIAM_USERS_METADATA_MOUNT_PATH = "metadata/awsroleiam_users";
replaced with single path for both iam and ec2

2021-01-07 13:11 UTC, msivatmob commented on tvaultapi/src/main/java/com/tmobile/cso/vault/api/controller/ControllerUtil.java
> +        AppRoleMetadataDetails appRoleMetadataDetails = new AppRoleMetadataDetails(RoleName);
created new model for AWS role AWSMetadataDetails.java and AWSRoleMetadata.java

2021-01-07 13:12 UTC, msivatmob commented on tvaultapi/src/main/java/com/tmobile/cso/vault/api/controller/ControllerUtil.java
> +	/**
Sure ,will take care in future commit.

2021-01-08 02:25 UTC, sarathmohan4 approved these changes

2021-01-08 03:15 UTC, merged