COCICCS-6024:Edit safe:Application name selected is not getting displayed
tmobile/t-vault pull request #698
Opened 2021-01-15 11:27 UTC by msivatmob

2021-01-15 11:27 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/tmobile/t-vault?pullRequest=698) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/tmobile/t-vault?pullRequest=698) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/tmobile/t-vault?pullRequest=698) it.</sub>

2021-01-18 06:21 UTC, sarathmohan4 submitted a review, later dismissed

2021-01-18 06:30 UTC, alexrajan3 requested changes
Please check the review comments

2021-01-18 06:30 UTC, alexrajan3 commented on tvaultapi/src/main/java/com/tmobile/cso/vault/api/utils/SafeUtils.java
> +import com.tmobile.cso.vault.api.model.SafeSecretCount;
Not used anywhere  - Remove this unwanted import

2021-01-18 06:30 UTC, alexrajan3 commented on tvaultapi/src/main/java/com/tmobile/cso/vault/api/service/SafesService.java
> +//import org.springframework.util.StringUtils;
Remove unwanted commented code

2021-01-18 07:04 UTC, msivatmob commented on tvaultapi/src/main/java/com/tmobile/cso/vault/api/utils/SafeUtils.java
> +import com.tmobile.cso.vault.api.model.SafeSecretCount;
Removed the import.

2021-01-18 07:05 UTC, msivatmob commented on tvaultapi/src/main/java/com/tmobile/cso/vault/api/service/SafesService.java
> +//import org.springframework.util.StringUtils;
Removed the commented line.

2021-01-18 07:42 UTC, merged