COCICCS-6191:AWS roCOCICCS-6191:AWS role policies of Safe, Cert, AD and IAM service account got removed when edited AAD AWS permission via UI
tmobile/t-vault pull request #735
Opened 2021-01-29 07:33 UTC by msivatmob

2021-01-29 07:33 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/tmobile/t-vault?pullRequest=735) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/tmobile/t-vault?pullRequest=735) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/tmobile/t-vault?pullRequest=735) it.</sub>

2021-01-29 11:42 UTC, sarathmohan4 requested changes

2021-01-29 11:42 UTC, sarathmohan4 commented on tvaultapi/src/main/java/com/tmobile/cso/vault/api/service/AWSAuthService.java
> +			throw new TVaultValidationException("Invalid inputs for the given AWS login type.policy is not an input parameter");
Can we updated message to something like, policies are not permitted during creation

2021-01-29 11:42 UTC, sarathmohan4 commented on tvaultapi/src/main/java/com/tmobile/cso/vault/api/service/AWSIAMAuthService.java
> +			throw new TVaultValidationException("Invalid inputs for the given aws login type.policy is not an input parameter");
can we update message

2021-01-29 11:51 UTC, msivatmob commented on tvaultapi/src/main/java/com/tmobile/cso/vault/api/service/AWSAuthService.java
> +			throw new TVaultValidationException("Invalid inputs for the given AWS login type.policy is not an input parameter");
Message updated

2021-01-29 11:51 UTC, msivatmob commented on tvaultapi/src/main/java/com/tmobile/cso/vault/api/service/AWSIAMAuthService.java
> +			throw new TVaultValidationException("Invalid inputs for the given aws login type.policy is not an input parameter");
updated the message

2021-02-02 06:26 UTC, alexrajan3 requested changes

2021-02-02 06:26 UTC, alexrajan3 commented on tvaultapi/src/main/resources/swaggernotes.properties
> +SelfSupportController.updateSafe.notes=<b>Updates Safe and its associated users, groups, roles.</b><br>\
Change "Updates" to "Update"

2021-02-02 06:32 UTC, msivatmob commented on tvaultapi/src/main/resources/swaggernotes.properties
> +SelfSupportController.updateSafe.notes=<b>Updates Safe and its associated users, groups, roles.</b><br>\
Changed.

2021-02-02 06:57 UTC, merged