COCICCS-6138:T-Vault Logging enhancements - More request tracing for …
tmobile/t-vault pull request #746
Opened 2021-02-03 12:36 UTC by msivatmob

…Safes

2021-02-03 12:37 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/tmobile/t-vault?pullRequest=746) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/tmobile/t-vault?pullRequest=746) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/tmobile/t-vault?pullRequest=746) it.</sub>

2021-02-04 01:46 UTC, alexrajan3 requested changes

2021-02-04 01:46 UTC, alexrajan3 commented on tvaultapi/src/main/java/com/tmobile/cso/vault/api/service/SafesService.java
> +				put(LogMessage.ACTION, TVaultConstants.CREATE_SDB).
TVaultConstants class should have only common constants. Include this value inside the same class itself.

2021-02-04 01:46 UTC, alexrajan3 commented on tvaultapi/src/main/java/com/tmobile/cso/vault/api/service/SafesService.java
> +					put(LogMessage.ACTION, TVaultConstants.CREATE_SDB).
Remove this from TVaultConstants

2021-02-04 01:46 UTC, alexrajan3 commented on tvaultapi/src/main/java/com/tmobile/cso/vault/api/service/SafesService.java
> +					put(LogMessage.ACTION, TVaultConstants.CREATE_SDB).
Remove this from TVaultConstants

2021-02-04 02:34 UTC, sarathmohan4 submitted a review, later dismissed

2021-02-04 03:41 UTC, msivatmob commented on tvaultapi/src/main/java/com/tmobile/cso/vault/api/service/SafesService.java
> +				put(LogMessage.ACTION, TVaultConstants.CREATE_SDB).
Constant values are included in same class itself.

2021-02-04 03:41 UTC, msivatmob commented on tvaultapi/src/main/java/com/tmobile/cso/vault/api/service/SafesService.java
> +					put(LogMessage.ACTION, TVaultConstants.CREATE_SDB).
Removed.

2021-02-04 03:41 UTC, msivatmob commented on tvaultapi/src/main/java/com/tmobile/cso/vault/api/service/SafesService.java
> +					put(LogMessage.ACTION, TVaultConstants.CREATE_SDB).
Removed.

2021-02-04 04:51 UTC, merged