Fix for external cert duplicate check in single san and multisan cert…
tmobile/t-vault pull request #870
Opened 2021-03-26 03:34 UTC by sarathmohan4

…ificate

2021-03-31 08:18 UTC, alexrajan3 submitted a review, later dismissed

2021-04-02 02:14 UTC, sivanag1974 requested changes

2021-04-02 02:14 UTC, sivanag1974 commented on tvaultapi/src/main/java/com/tmobile/cso/vault/api/service/SSLCertificateService.java
> +                    getCertificateFromNCLM(sslCertificateRequest.getCertificateName(),containerId, certManagerLogin):null;
Need some comments why this is done

2021-04-02 02:14 UTC, sivanag1974 commented on tvaultapi/src/main/java/com/tmobile/cso/vault/api/service/SSLCertificateService.java
> +                .put(LogMessage.ACTION, SSLCertificateConstants.GENERATE_SSL_CERTIFICTAE)
Name of the method is getCertificate, but the message logged is GENERATE_SSL_CERTIFICATE, why?

2021-04-07 10:58 UTC, merged